spring:
  datasource:
    url: jdbc:mysql://47.99.73.15:3306/learn2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  rabbitmq:
    host: 47.99.73.15
    username: guest
    password: guest
    #开启手动ack  控制消息在MQ的删除 重发
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    database: 12
    host: 47.99.73.15
    port: 6379