server:
  port: 12306
spring:
  application:
    name: miao-sha
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.99.73.15:3306/learn?useUnicode=true&characterEncoding=utf-8&useSSL=false
