spring:
  datasource:
    url: jdbc:mysql://47.99.73.15:3306/learn?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  rabbitmq:
    host: 47.99.73.15
    username: guest
    password: guest
    #\u5F00\u542F\u53D1\u5E03\u786E\u8BA4\u673A\u5236
    publisher-confirms: true