spring:
  datasource:
    url: jdbc:mysql://47.99.73.15:3306/learn?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  rabbitmq:
    host: 47.99.73.15
    username: guest
    password: guest
    #消息发送成功后 ack确认
    publisher-confirms: true